// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vlms.Infrastructure;

#nullable disable

namespace Vlms.Infrastructure.Migrations
{
    [DbContext(typeof(VlmsDbContext))]
    [Migration("20260717224824_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vlms.Domain.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntraObjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Vlms.Domain.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("BlobKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentLessonCompletionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentLessonCompletionId")
                        .IsUnique();

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("Vlms.Domain.ConsentRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("ApprovedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("DataSharingConsent")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<bool>("PhotoMediaConsent")
                        .HasColumnType("bit");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubmittedByParentId")
                        .HasColumnType("int");

                    b.Property<bool>("TransportOffsiteConsent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubmittedByParentId");

                    b.ToTable("ConsentRecords");
                });

            modelBuilder.Entity("Vlms.Domain.ConsentSensitiveDetails", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ConsentRecordId")
                        .HasColumnType("int");

                    b.Property<string>("DietarySEN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyMedicalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsentRecordId")
                        .IsUnique();

                    b.ToTable("ConsentSensitiveDetails");
                });

            modelBuilder.Entity("Vlms.Domain.DbsCheck", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("CheckDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ExpiryDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TeacherUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherUserId");

                    b.ToTable("DbsChecks");
                });

            modelBuilder.Entity("Vlms.Domain.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentBlobKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("Vlms.Domain.LessonChangeProposal", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ApprovalComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<int>("ChangeType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("ProposedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("ProposedContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResubmissionOfProposalId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("LessonId");

                    b.HasIndex("ProposedByUserId");

                    b.HasIndex("ResubmissionOfProposalId");

                    b.ToTable("LessonChangeProposals");
                });

            modelBuilder.Entity("Vlms.Domain.ParentGuardian", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ParentGuardians");
                });

            modelBuilder.Entity("Vlms.Domain.Rank", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ranks");
                });

            modelBuilder.Entity("Vlms.Domain.RankBadge", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ImageBlobKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.ToTable("RankBadges");
                });

            modelBuilder.Entity("Vlms.Domain.SensitiveDataAccessLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessType")
                        .HasColumnType("int");

                    b.Property<DateTime>("AccessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Entity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SensitiveDataAccessLogs");
                });

            modelBuilder.Entity("Vlms.Domain.Student", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedTeacherUserId")
                        .HasColumnType("int");

                    b.Property<int>("CurrentRankId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EnrolmentDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTeacherUserId");

                    b.HasIndex("CurrentRankId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Vlms.Domain.StudentBadge", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RankBadgeId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RankBadgeId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentBadges");
                });

            modelBuilder.Entity("Vlms.Domain.StudentGuardianLink", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ParentGuardianId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "ParentGuardianId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ParentGuardianId");

                    b.ToTable("StudentGuardianLinks");
                });

            modelBuilder.Entity("Vlms.Domain.StudentLessonCompletion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CompletedByUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsReversed")
                        .HasColumnType("bit");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReversedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByUserId");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentLessonCompletions");
                });

            modelBuilder.Entity("Vlms.Domain.StudentRankProgress", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RankId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentRankProgresses");
                });

            modelBuilder.Entity("Vlms.Domain.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("UserId", "Role");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Vlms.Domain.Certificate", b =>
                {
                    b.HasOne("Vlms.Domain.StudentLessonCompletion", "StudentLessonCompletion")
                        .WithOne("Certificate")
                        .HasForeignKey("Vlms.Domain.Certificate", "StudentLessonCompletionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentLessonCompletion");
                });

            modelBuilder.Entity("Vlms.Domain.ConsentRecord", b =>
                {
                    b.HasOne("Vlms.Domain.AppUser", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vlms.Domain.Student", "Student")
                        .WithMany("ConsentRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vlms.Domain.ParentGuardian", "SubmittedByParent")
                        .WithMany("SubmittedConsentRecords")
                        .HasForeignKey("SubmittedByParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("Student");

                    b.Navigation("SubmittedByParent");
                });

            modelBuilder.Entity("Vlms.Domain.ConsentSensitiveDetails", b =>
                {
                    b.HasOne("Vlms.Domain.ConsentRecord", "ConsentRecord")
                        .WithOne("SensitiveDetails")
                        .HasForeignKey("Vlms.Domain.ConsentSensitiveDetails", "ConsentRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsentRecord");
                });

            modelBuilder.Entity("Vlms.Domain.DbsCheck", b =>
                {
                    b.HasOne("Vlms.Domain.AppUser", "TeacherUser")
                        .WithMany()
                        .HasForeignKey("TeacherUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TeacherUser");
                });

            modelBuilder.Entity("Vlms.Domain.Lesson", b =>
                {
                    b.HasOne("Vlms.Domain.Rank", "Rank")
                        .WithMany("Lessons")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("Vlms.Domain.LessonChangeProposal", b =>
                {
                    b.HasOne("Vlms.Domain.AppUser", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vlms.Domain.Lesson", "Lesson")
                        .WithMany("ChangeProposals")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vlms.Domain.AppUser", "ProposedByUser")
                        .WithMany()
                        .HasForeignKey("ProposedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vlms.Domain.LessonChangeProposal", "ResubmissionOfProposal")
                        .WithMany()
                        .HasForeignKey("ResubmissionOfProposalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ApproverUser");

                    b.Navigation("Lesson");

                    b.Navigation("ProposedByUser");

                    b.Navigation("ResubmissionOfProposal");
                });

            modelBuilder.Entity("Vlms.Domain.RankBadge", b =>
                {
                    b.HasOne("Vlms.Domain.Rank", "Rank")
                        .WithMany("RankBadges")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");
                });

            modelBuilder.Entity("Vlms.Domain.Student", b =>
                {
                    b.HasOne("Vlms.Domain.AppUser", "AssignedTeacherUser")
                        .WithMany()
                        .HasForeignKey("AssignedTeacherUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vlms.Domain.Rank", "CurrentRank")
                        .WithMany()
                        .HasForeignKey("CurrentRankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTeacherUser");

                    b.Navigation("CurrentRank");
                });

            modelBuilder.Entity("Vlms.Domain.StudentBadge", b =>
                {
                    b.HasOne("Vlms.Domain.RankBadge", "RankBadge")
                        .WithMany("StudentBadges")
                        .HasForeignKey("RankBadgeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vlms.Domain.Student", "Student")
                        .WithMany("Badges")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RankBadge");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Vlms.Domain.StudentGuardianLink", b =>
                {
                    b.HasOne("Vlms.Domain.AppUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vlms.Domain.ParentGuardian", "ParentGuardian")
                        .WithMany("StudentLinks")
                        .HasForeignKey("ParentGuardianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vlms.Domain.Student", "Student")
                        .WithMany("GuardianLinks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ParentGuardian");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Vlms.Domain.StudentLessonCompletion", b =>
                {
                    b.HasOne("Vlms.Domain.AppUser", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vlms.Domain.Lesson", "Lesson")
                        .WithMany("Completions")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vlms.Domain.Student", "Student")
                        .WithMany("Completions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompletedByUser");

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Vlms.Domain.StudentRankProgress", b =>
                {
                    b.HasOne("Vlms.Domain.Rank", "Rank")
                        .WithMany()
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vlms.Domain.Student", "Student")
                        .WithMany("RankProgressHistory")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rank");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Vlms.Domain.UserRole", b =>
                {
                    b.HasOne("Vlms.Domain.AppUser", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Vlms.Domain.AppUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Vlms.Domain.ConsentRecord", b =>
                {
                    b.Navigation("SensitiveDetails");
                });

            modelBuilder.Entity("Vlms.Domain.Lesson", b =>
                {
                    b.Navigation("ChangeProposals");

                    b.Navigation("Completions");
                });

            modelBuilder.Entity("Vlms.Domain.ParentGuardian", b =>
                {
                    b.Navigation("StudentLinks");

                    b.Navigation("SubmittedConsentRecords");
                });

            modelBuilder.Entity("Vlms.Domain.Rank", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("RankBadges");
                });

            modelBuilder.Entity("Vlms.Domain.RankBadge", b =>
                {
                    b.Navigation("StudentBadges");
                });

            modelBuilder.Entity("Vlms.Domain.Student", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("Completions");

                    b.Navigation("ConsentRecords");

                    b.Navigation("GuardianLinks");

                    b.Navigation("RankProgressHistory");
                });

            modelBuilder.Entity("Vlms.Domain.StudentLessonCompletion", b =>
                {
                    b.Navigation("Certificate");
                });
#pragma warning restore 612, 618
        }
    }
}
